augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    drop_block: true
  name: resnet12_drop
batch_size: 128
classifier:
  kwargs:
    num_class: 351
    nFeat: 640
    kernel: 1
    groups: 320
  name: DMF
data_root: /home/qinhaonan/.vscode-server/data/dataset/tiered_imagenet
deterministic: true
device_ids: 0,1,2,3
episode_size: 8
epoch: 120
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/DMF.yaml
- backbones/resnet12_drop.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    T_max: 120
    eta_min: 0
  name: CosineAnnealingLR
warmup: 10
n_gpu: 4
optimizer:
  kwargs:
    lr: 0.05
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
  other: null
parallel_part:
- emb_func
pretrain_path: null
query_num: 6
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 2147483647
shot_num: 5
tag: null
tb_scale: 3.3333333333333335
test_episode: 1200
test_epoch: 5
test_query: 6
test_shot: 5
test_way: 5
train_episode: 2000
use_memory: false
way_num: 5
