augment: true
augment_method: COSOCAugment
augment_times: 7
augment_times_query: 7
backbone:
  kwargs: null
  name: resnet12_cosoc
batch_size: 128
classifier:
  kwargs: 
    alpha: 0.8
    beta: 0.8
    num_patches: 7
    fsl_alg: CC
    num_classes: 64
    scale_cls: 10
  name: COSOC
data_root: /tmp/miniImageNet--ravi
feature_image_and_crop_id: /tmp/miniImageNet--ravi/feature_image_and_crop_id.pkl
position_list: /tmp/miniImageNet--ravi/position_list.npy
deterministic: true
device_ids: 1
episode_size: 1
epoch: 3 # TODO
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/COSOC.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 10
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.005
    weight_decay: 0.0005
  name: Adam
  other: null
parallel_part:
- emb_func
port: 48828
pretrain_path: /tmp/miniImageNet--ravi/backbone.pth
query_num: 15
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 0
shot_num: 1
tag: null
tb_scale: 3.3333333333333335
test_episode: 600
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
train_episode: 2000
use_memory: false
way_num: 5
workers: 16
